### ISSUE TITLE
Cannot link files any more

### ISSUE THREAD

**Issue by xeno-by** [djspiewak/cccp#10]
With the latest stable version of jEdit (4.4.2) and the latest version of CCCP (commit b33ecd02c3) I cannot link files. Unfortunately, the only menu item being available in Plugins > CCCP is "Unlink file". Neither clicking this menu item, nor creating a new buffer help. I also tried uninstalling jEdit and installing it again - with the same luck.

**Comment by djspiewak** [comment]
Er, um, this is embarrassing.  :-)  I made a mistake in the plugin properties configuration.  The command was still available (`cccp.link`), but the menu didn't expose it.  I think this establishes that I pretty much never use the menus in my editor.

Fixed in the latest push.
