### ISSUE TITLE
Difficult to find out what's going on

### ISSUE THREAD

**Issue by xeno-by** [djspiewak/cccp#12]
Even after I made logging cross-platform (https://github.com/djspiewak/cccp/pull/11), jEdit still does not want to work. 

At the moment I don't have the time to dive into code, so I just tried to find what's going on from the user perspective, and here what I've seen:
1) I opened jEdit, opened a file and clicked CCCP > Link file..., then typed in a random name and... nothing happened: jEdit neither told me that everything is fine, nor crashed or displayed an error,
2) I checked the server console - nothing,
3) I also checked server logs - nothing as well.

Also, having both "Link file..." and "Unlink file" menu items enabled at all times is misleading - this also might be a hint for a user, but it is not.

**Comment by djspiewak** [comment]
Looking into this now.  There should have at least been indication that the agent had received the link command (e.g. something like "Handling RPC `(swank:link-file ...)`").  In regards to the Link and Unlink being enabled simultaneously, this isn't something I have control over (unfortunately).  I do agree that this should hint the user, but jEdit doesn't give me the ability to enable or disable commands at will.  Right now, I ignore unlink actions for non-linked buffers.  We should probably change this to throw up an error.

**Comment by djspiewak** [comment]
I'm going to close this issue for now.  I can't break the jEdit sync anymore.  There is definitely still a need for better user feedback.  This effort will be ongoing.
