### ISSUE TITLE
jEdit sync fails with 'retain item count not positive'

### ISSUE THREAD

**Issue by candera** [djspiewak/cccp#14]
When running two jEdit instances on the same machine, edits in either result in the following log trace: 

<pre>
Handling chunk: (:swank-rpc (swank:init-connection (:protocol "http" :host "localhost" :port 8585)) 1)
Initializing connection: http://localhost:8585
Handling chunk: (:swank-rpc (swank:link-file "log" "/tmp/cccp3431393040812377050.log") 2)
Linking file: log -> /tmp/cccp3431393040812377050.log
Handling chunk: (:swank-rpc (swank:edit-file "/tmp/cccp3431393040812377050.log" (:retain 216 :insert "a" :retain 0)) 3)
Handling chunk: (:swank-rpc (swank:edit-file "/tmp/cccp3431393040812377050.log" (:retain 217 :insert "b" :retain 0)) 4)
</pre>

But no edits appear in the other jEdit instance.

Sniffing the network traffic between the agent and the plugin reveals the following error being returned: 

<pre>
0000df(:return (:abort 201 "Attempt to build ill-formed operation (ViolationCollector[2: ill-formed: retain item count not positive at original document position 217 / resulting document position 218])
</pre>

Why doesn't this error appear in the log?

I will try this with emacs and see if the same problem crops up.

**Comment by candera** [comment]
Not seeing this in emacs. Might be my jEdit setup is wrong. My emacs setup is now working sufficiently that I probably won't spend much time with jEdit.

**Comment by djspiewak** [comment]
Essentially, it means that my jEdit plugin has a bug.  Specifically, I shouldn't be writing null retains.  The exception doesn't appear in the agent log because I forgot to log it.  I thought I had put in a change to log every response, but apparently not.  I'll have to add that.

**Comment by djspiewak** [comment]
Should be fixed in the latest push.
