### ISSUE TITLE
'retain item count not positive'

### ISSUE THREAD

**Issue by candera** [djspiewak/cccp#18]
# Background

When I was trying to get jEdit and emacs to talk to each other, I was unsuccessful. After some digging, it looks like the jEdit plugin is getting errors back for every edit-file operation. 
# Steps to Reproduce
- Start a server
- Start jEdit
- Choose "Link File" from the CCCP plugin menu
- Type any character
- Observe the entries in the log below
# Error Log

<pre>
Handling chunk: (:swank-rpc (swank:init-connection (:protocol "http" :host "localhost" :port 8585)) 1)
Initializing connection: http://localhost:8585
Handling chunk: (:swank-rpc (swank:link-file "abc" "/home/candera/projects/cccp/Untitled-1") 2)
Linking file: abc -> /home/candera/projects/cccp/Untitled-1
Handling chunk: (:swank-rpc (swank:edit-file "/home/candera/projects/cccp/Untitled-1" (:retain 0 :insert " " :retain 0)) 3)
Sending chunk: (:return (:abort 201 "Attempt to build ill-formed operation (ViolationCollector[1: ill-formed: retain item count not positive at original document position 0 / resulting document position 0]): __0; ") 3)
</pre>

**Comment by djspiewak** [comment]
This shouldn't be happening.  I actually filter retains to be strictly positive in jEdit.  Are you sure you have the latest version of the jEdit CCCP plugin?

**Comment by candera** [comment]
I didn't even have jEdit installed until today, and I checked that I'm
running latest. I will verify that I didn't screw something up and
drop a comment here later with my results.

On Fri, Dec 9, 2011 at 4:30 PM, Daniel Spiewak
reply@reply.github.com
wrote:

**Comment by candera** [comment]
Confirmed. I did an sbt clean and stage in the cccp-jedit-plugin project, checked the filetimes, restarted jEdit, and I get the same error.

**Comment by djspiewak** [comment]
So, this basically demonstrates that I'm really bad at testing my own code.  :-(  When I fixed the non-positive retain count, I fixed it in the wrong place.  I have implemented a different fix (in the right place) and run your case successfully.
