### ISSUE TITLE
sbt crashes on build when using OpenJDK

### ISSUE THREAD

**Issue by candera** [djspiewak/cccp#5]
When attempting to compile cccp via sbt, I get the following error:

<pre>

[info] Compiling 1 Scala source to /home/candera/projects/cccp/project/target/scala-2.9.1/sbt-0.11.1/classes...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xb4c1ef2c, pid=26414, tid=3077864304
#
# JRE version: 6.0_22-b22
# Java VM: OpenJDK Server VM (20.0-b11 mixed mode linux-x86 )
# Derivative: IcedTea6 1.10.4
# Distribution: Ubuntu 11.04, package 6b22-1.10.4-0ubuntu1~11.04.1
# Problematic frame:
# J  scala.tools.nsc.symtab.Types$TypeMap.mapOver(Lscala/tools/nsc/symtab/Types$Type;)Lscala/tools/nsc/symtab/Types$Type;
#
# An error report file with more information is saved as:
# /home/candera/projects/cccp/hs_err_pid26414.log
#
# If you would like to submit a bug report, please include
# instructions how to reproduce the bug and visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-6/
#
/home/candera/bin/sbt: line 3: 26414 Aborted                 (core dumped) java -Xmx512M -jar `dirname $0`/sbt-launch.jar "$@"
</pre>

The referenced log file is available here: https://gist.github.com/1376864

**Comment by candera** [comment]
This doesn't repro when using the Sun JDK: 

```
sudo update-java-alternatives -s java-6-sun
sbt stage
```

Works fine.

**Comment by djspiewak** [comment]
Given that this is apparently an issue with the IcedTea VM, I'm going to close this.  I'm not sure there's anything I can do about the Scala compiler triggering a segfault.  :-)

**Comment by candera** [comment]
Fair enough.
