### ISSUE TITLE
Build fails when jEdit is not available

### ISSUE THREAD

**Issue by candera** [djspiewak/cccp#6]
When jEdit is not available, the build fails with the following error:

<pre>
[cccp (master)(-solo-)⚡] sbt stage
[info] Loading project definition from /home/candera/projects/cccp/project
[info] Set current project to cccp (in build file:/home/candera/projects/cccp/)
[info] Copying runtime environment to ./dist....
[info] Copying runtime environment to ./dist....
[error] {file:/home/candera/projects/cccp/}cccp-jedit-client/compile:unmanaged-jars: jedit.jar was not found. please, set the JEDIT_HOME environment variable
[error] Total time: 0 s, completed Nov 20, 2011 6:42:38 AM
</pre>

**Comment by djspiewak** [comment]
/me sighs

I gave you incomplete instructions on how to build the server and agent.  My mistake.  :-(  What you actually need to do is as follows:

```
$ sbt
> project cccp-agent
> stage
> project cccp-server
> stage
> exit
```

The `sbt` command by itself drops you into the SBT shell, which lets you run multiple commands in a stateful environment.  The server and agent are sub-projects, and so building them requires moving into those project specifically.  The jEdit client is another sub-project, and one that requires jEdit to build.

**Comment by candera** [comment]
Thanks, that helps.

Would it make sense for the jEdit plugin to be a separate project entirely?

On Sun, Nov 20, 2011 at 12:10 PM, Daniel Spiewak
reply@reply.github.com
wrote:

**Comment by djspiewak** [comment]
> Would it make sense for the jEdit plugin to be a separate project entirely?

Hmm, actually yes, I think that does make more sense.  I had initially been planning on shoving all of the editor-specific clients into the `clients/` directory, but that's really not the most modular repository design.  In any case, you've split cccp-mode out as its own project, so it's probably better to stay consistent with that.

I'll look into this over the holiday.

**Comment by candera** [comment]
I think it makes sense that there be a single _package_ that _users_
can get with editor support for everything we know about, but that's a
separate question from how developers consume it. Of course, building
the batteries-included package is more complicated, especially around
versioning.

I actually don't have a huge problem with putting the emacs mode into
the giant repo if we think that's best.

On Tue, Nov 22, 2011 at 10:14 AM, Daniel Spiewak
reply@reply.github.com
wrote:

**Comment by djspiewak** [comment]
> I actually don't have a huge problem with putting the emacs mode into the giant repo if we think that's best.

Nah, I think splitting is better for development, merging will be better for consumption.  If we can find a way to build a proper bundle of cccp-mode + agent as well as jEdit Plugin + agent without having them in the same repo, I think that would be ideal.
